#!/usr/bin/env bash

# FOR DEV PURPOSE ONLY
# Get all servername from nginx conf, generate custom hosts file and symlink it from here
# Usage: sh genhosts.sh

hostsfile=/etc/hosts
customhosts=$(pwd)/hosts
confdir=$(pwd)/nginx/conf.d/*.conf

if [ -f $customhosts ]; then
    echo "Found generated hosts under $customhosts. Overwriting..."
    cat /dev/null > $customhosts
fi

echo "########################" >> $customhosts
echo "# DO NOT EDIT THIS FILE" >> $customhosts
echo "# Create or modify server names under $confdir instead" >> $customhosts
echo "########################" >> $customhosts

echo "127.0.1.1 $(cat /etc/hostname)" >> $customhosts
echo "" >> $customhosts
echo "#### nginx hostnames ####" >> $customhosts

# @NOTE: $1 = server_name, $2 = first domain, $3 = second domain, $n = n domain
# Remove entry begining with #, remove ending ;
# Final sort them
cat $confdir | grep server_name \
    | sed '/^#/ d' | sed 's/;//' \
    | awk -F ' ' '{print "127.0.0.1 " $2 " " $3 " " $4}' \
    | sort -n \
    >> $customhosts

sudo ln -nfs $customhosts $hostsfile
echo "The hosts file has been generated and symlinked."

docker-compose restart web
echo "Nginx has been reload."